# Generated by Django 3.2.20 on 2023-08-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('image', models.ImageField(default='static/pics/Picture7.png', upload_to='static/pics')),
                ('ID', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('customer_type', models.CharField(max_length=50)),
                ('events_count', models.PositiveIntegerField(default=0)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('image', models.ImageField(default='static/pics/Picture7.png', upload_to='static/pics')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('event_type', models.TextField()),
                ('event_date', models.DateField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('image', models.ImageField(default='static/pics/pack.png', upload_to='static/pics')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('package_details', models.TextField()),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('image', models.ImageField(default='static/pics/event123.png', upload_to='static/pics')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('venue', models.CharField(max_length=255)),
                ('number_of_attendees', models.PositiveIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_for_customer', to='oz_pro.customer')),
                ('service_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_for_service_package', to='oz_pro.servicepackage')),
            ],
        ),
    ]
