# Generated by Django 4.2.4 on 2023-08-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oz_pro", "0004_alter_lead_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="image",
            field=models.ImageField(default="anonymous.png", upload_to="static"),
        ),
    ]
