# Generated by Django 4.2.4 on 2023-08-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oz_pro", "0006_rename_event_type_and_details_lead_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="image",
            field=models.ImageField(default="Picture7.png", upload_to="static/pics"),
        ),
    ]
