# Generated by Django 4.2.4 on 2023-08-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oz_pro", "0007_customer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(default="event.png", upload_to="static/pics"),
        ),
    ]
