# Generated by Django 4.2.4 on 2023-08-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oz_pro", "0008_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicepackage",
            name="image",
            field=models.ImageField(default="service.png", upload_to="static/pics"),
        ),
    ]
