# Generated by Django 4.2.3 on 2023-08-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oz_pro", "0009_servicepackage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="image",
            field=models.ImageField(default="package.png", upload_to="static/pics"),
        ),
    ]
