# Generated by Django 4.2.3 on 2023-08-18 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oz_pro", "0010_alter_servicepackage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepackage",
            name="image",
            field=models.ImageField(default="pack.png", upload_to="static/pics"),
        ),
    ]
