# Generated by Django 4.2.3 on 2023-08-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oz_pro", "0011_alter_servicepackage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="image",
            field=models.ImageField(
                default="static/pics/Picture7.png", upload_to="static/pics"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                default="static/pics/event.png", upload_to="static/pics"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="image",
            field=models.ImageField(
                default="static/pics/Picture7.png", upload_to="static/pics"
            ),
        ),
        migrations.AlterField(
            model_name="servicepackage",
            name="image",
            field=models.ImageField(
                default="static/pics/pack.png", upload_to="static/pics"
            ),
        ),
    ]
