# Generated by Django 4.2.3 on 2023-08-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oz_pro", "0012_alter_customer_image_alter_event_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="events_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="event",
            name="image",
            field=models.ImageField(
                default="static/pics/event123.png", upload_to="static/pics"
            ),
        ),
    ]
